services:
  backend:
    build: .
    container_name: backend
    command: python -m backend
    volumes:
      - ./backend:/srv/app
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
  frontend:
    build:
      context: ./schedule
    container_name: frontend
    command: npm run dev 
    volumes:
      - ./schedule:/srv/app
    ports:
      - "5173:5173"
      - "35729:35729"
    networks:
      - frontend

networks:
  backend:
  frontend: